####################################################################
#    ____       _   _              _____                           #
#   | __ )  ___| |_| |_ ___ _ __  |_   _|__  __ _ _ __ ___  ___    #
#   |  _ \ / _ \ __| __/ _ \ '__|   | |/ _ \/ _` | '_ ` _ \/ __|   #
#   | |_) |  __/ |_| ||  __/ |      | |  __/ (_| | | | | | \__ \   #
#   |____/ \___|\__|\__\___|_|      |_|\___|\__,_|_| |_| |_|___/   #
#                                                                  #
####################################################################

# Thank you for downloading better teams, before configuring the file here are some useful links for you:
# BetterTeams spigot page: https://www.spigotmc.org/resources/better-teams.17129/
#
# Found a bug? Report it here: https://github.com/booksaw/BetterTeams/issues/new/choose (Use the bug template)
#
# Is there something annoying you about how the plugin works, or something missing? 
# Make suggestions for the future of the plugin here: https://github.com/booksaw/BetterTeams/issues/new/choose (Use the feature template)
#
# If you need to edit the messages which are sent to the user, look in the messages.yml file

# This is the value to determine if the chat prefix is enabled
# - If this is enabled a prefix [TeamName] will be displayed at the begining of chat messages.
# - If the player is not in a team, nothing will be displayed
# - This is the chat prefix for when players speak, this will not disable the prefix before messages generated by the plugin (see prefixFormat [below] to change that)
#
# Possible values: [true, false]
prefix: true

# Set the format for the prefix of all messages sent to the user
# - Any chat colors can be used, for a reference see: https://www.spigotmc.org/attachments/example2-png.188806/
# - Ensure your prefix is surrounded by single quotes --> '' <-- else there is a chance it will not work correctly 
# - It is recommended to leave a space after the prefix within the quotation marks, so it does not look like this [prefix]message but instead [prefix] message
# - To disable the prefix, set the value to be ''
#
# Possible values: [Any text, any chat colours using the reference '&']
prefixFormat: '&7[&6BetterTeams&7] '

# This is used set a maximum size for a team.
# - If this feature is unwanted, set the teamLimit to -1 and there will be unlimited places in each team
# - Keep this value reasonable, as Java cannot cope with larger numbers (over 2 billion), so if you want the team to be limitless, set the value to -1 instead of something large
#
# Possible values: [-1, any positive whole number]
teamLimit: -1

# This is used to limit the length of a team name (if chat prefixes are enabled, this will stop the team names clogging up the chat)
# - If this feature is unwanted, set the teamLimit to -1 and team name lengths will be unlimited
#
# Possible values: [-1, any positive whole number]
maxTeamLength: 12

# This is used to toggle if teams can attack members of their own team
# - If this is enabled, memebers of the same team will not be able to damage each other
# - If you change this feature, you will need to restart the server for the value to update (does not work with /teama realod)
# 
# Possible values: [true, false]
disableCombat: true

# This will by extension of disable combat also stop players from applying negative potion effects to members of their team
# - If disableCombat is set to false (above) potion effects will never be disabled
# - If you change this feature, you will need to restart the server for the value to update (does not work with /teama realod)
#
# Posssible values: [True - Negative potions should be disabled for members of the same team, False - Negative potions are allowed for memebers of the same team ]
disablePotions: true

# This is used to toggle if players can harm themselves with potions or arrows (while they are on a team) 
# - If this is enabled, players cannot apply negative potion effects to themselves or hit themselves with arrows
# - If you change this feature, you will need to restart the server for the value to update (does not work with /teama realod)
# - If a player is not on a team, they will hit themselves with potions regardless of what value this opion takes
#
# Possible values: [true - Potion effects will damage the player who threw them, false - Potion effects will not damage the palyer who threw them]
playerDamageSelf: true

# This is a list of all the team names that are blacklisted on your server (include any names of teams that you want to ban)
# - This will only work if the name exactly fits the text in the blacklist (not case sensitive) else it will be up to your servers moderation team to deal with the offence 
#
# Possible values: [Any String (surround with '')]
blacklist:
   - 'betterteamsisbad'
   
# This is the color of the command in the help menu, this can be changed 
#
# Possible values: [Any chat color code]
helpCommandColor: 'b'

# This is the color of the message which comes with the command in the help menu, this can be changed 
#
# Possible values: [Any chat color code]
helpDescriptionColor: '6'

# If you are using holographics displays, this is how many of the top teams will be displayed on the hologram
#
# Possible values: [Any positive whole number]
maxHologramLines: 10 

# This is used to configure if player names should be changed (display the team name of a player above their head
#
# Possible values: [True, False]
displayTeamName: true

# Do not edit this value, this is used to check the config is up to date with the lastest version of the plugin (if it is not, it will be automatically updated)
version: 2
