# ------- Discord webhook manager -------
# But how do I create a discord webhook?
# Read this article: https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks

# The webhook URL of your webhook.
hookURL: "WEBHOOKURL_HERE"

# If you disabled support for webhooks these settings won't matter
# You can change for what specific events the webhook should be triggered.
# For example, if you set the create-hook option to true the webhook will send a message
# on team creation.
create-hook: false
disband-hook: false
player-left-hook: false
team-nameChange-hook: false
team-chat: false